SaleDoanInbound/Models/DSKhachHangViewModel.cs
using Data.Models_IB;
using Data.Models_QLT;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SaleDoanInbound.Models
{
    public class DSKhachHangViewModel
    {
        public KhachHang KhachHang { get; set; }
        public Khachtour KhachTour { get; set; }
        public IEnumerable<KhachHang> KhachHangs { get; set; }
        public Tour Tour { get; set; }
        public IEnumerable<ListViewModel> GioiTinhs { get; set; }

        public IEnumerable<Khachtour> ListDsKhach { get; set; }
    }
}

SaleDoanInbound/Controllers/DSKhachHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data.Models_IB;
using Data.Models_QLT;
using Data.Repository;
using Data.Services;
using Data.Utilities;
using Microsoft.AspNetCore.Mvc;
using SaleDoanInbound.Models;

namespace SaleDoanInbound.Controllers
{
    public class DSKhachHangsController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IDSKhachHangService _dSKhachHangService;

        [BindProperty]
        public DSKhachHangViewModel DSKhachHangVM { get; set; }

        public DSKhachHangsController(IUnitOfWork unitOfWork, IDSKhachHangService dSKhachHangService)
        {
            _unitOfWork = unitOfWork;
            _dSKhachHangService = dSKhachHangService;

            DSKhachHangVM = new DSKhachHangViewModel()
            {
                KhachHang = new Data.Models_IB.KhachHang(),
                Tour = new Data.Models_IB.Tour(),
                GioiTinhs = ListGioiTinh().OrderByDescending(x => x.GioiTinhName)
            };
        }

        private IEnumerable<ListViewModel> ListGioiTinh()
        {
            return new List<ListViewModel>()
            {
                //new ListViewModel(){GioiTinhId = "-- Select --", GioiTinhName = "-- Select --"},
                new ListViewModel(){GioiTinhId = "True", GioiTinhName = "Nam"},
                new ListViewModel(){GioiTinhId = "False", GioiTinhName = "Nữ"}
            };
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> KhachHangCreatePartial(long tourId)
        {

            DSKhachHangVM.Tour = _unitOfWork.tourRepository.GetById(tourId);
            DSKhachHangVM.KhachHang.TourId = DSKhachHangVM.Tour.Id;

            //DSKhachHangVM.KhachHangs = await _unitOfWork.dSKhachHangRepository.FindAsync(x => x.TourId == tourId);

            return PartialView(DSKhachHangVM);
        }

        public async Task<IActionResult> DSKhachHangPartial(long tourId)
        {

            DSKhachHangVM.Tour = _unitOfWork.tourRepository.GetById(tourId);
            //DSKhachHangVM.KhachHangs = await _unitOfWork.dSKhachHangRepository.FindIncludeOneAsync(x => x.Tour, y => y.TourId == tourId);

            //DSKhachHangVM.KhachHangs = await _unitOfWork.dSKhachHangRepository.FindAsync(x => x.TourId == tourId && x.Del == false);
            var hd = _unitOfWork.khachTourRepository.Find(x => x.Sgtcode == DSKhachHangVM.Tour.Sgtcode && x.Del == false).OrderBy(x => x.Stt).ToList();

            DSKhachHangVM.ListDsKhach = hd;
            return PartialView(DSKhachHangVM);
        }

        [HttpPost, ActionName("KhachHangCreatePartialPost")]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> KhachHangCreatePartialPost()
        {
            var tour = await _unitOfWork.tourRepository.GetByLongIdAsync(DSKhachHangVM.KhachHang.TourId);

            // from login session
            var user = HttpContext.Session.Gets<User>("loginUser").SingleOrDefault();
            if (ModelState.IsValid)
            {
                try
                {

                    // ghi log
                    DSKhachHangVM.KhachHang.LogFile = "-User tạo: " + user.Username + " vào lúc: " + System.DateTime.Now.ToString(); // user.Username

                    // SaleDoanIB
                    DSKhachHangVM.KhachHang.Sgtcode = tour.Sgtcode;
                    _unitOfWork.dSKhachHangRepository.Create(DSKhachHangVM.KhachHang);
                     // await _unitOfWork.Complete();
                    // qltour
                    Khachtour khachtour = new Khachtour()
                    {
                        Sgtcode = tour.Sgtcode,
                        Stt = DSKhachHangVM.KhachHang.STT,
                        Makh = DSKhachHangVM.KhachHang.MaKH,
                        Hoten = DSKhachHangVM.KhachHang.TenKH,
                        Ngaysinh = DSKhachHangVM.KhachHang.NgaySinh,
                        Phai = DSKhachHangVM.KhachHang.GioiTinh,
                        Diachi = DSKhachHangVM.KhachHang.DiaChi,
                        Quoctich = DSKhachHangVM.KhachHang.QuocTich,
                        Loaiphong = DSKhachHangVM.KhachHang.LoaiPhong,
                        Cmnd = DSKhachHangVM.KhachHang.CMND.ToString(),
                        Hochieu = DSKhachHangVM.KhachHang.HoChieu,
                        Del = false,
                        Visa = DSKhachHangVM.KhachHang.Visa,
                        YeuCauVisa = DSKhachHangVM.KhachHang.YeuCauVisa,
                        Logfile = DSKhachHangVM.KhachHang.LogFile
                    };

                    _unitOfWork.khachTourRepository.Create(khachtour);

                    await _unitOfWork.Complete();
                    //SetAlert("Thêm mới thành công.", "success");
                    //return Redirect(strUrl);

                }
                catch (Exception ex)
                {
                    SetAlert(ex.Message, "error");
                    ModelState.AddModelError("", ex.Message);

                    return Json(new
                    {
                        status = false
                    });
                }

                return Json(new
                {
                    status = true
                });

            }
            return Json(new
            {
                status = false
            });

        }

        public IActionResult KhachHangEditPartial(decimal id)
        {
            if (id == 0)
                return NotFound();

            var khachtour = _unitOfWork.khachTourRepository.GetById(id);
            //BienNhanVM.BienNhan.TourIBId = tourIBId;

            if (khachtour == null)
                return NotFound();

            DSKhachHangVM.KhachTour = khachtour;
            DSKhachHangVM.Tour = _unitOfWork.tourRepository.Find(x => x.Sgtcode == khachtour.Sgtcode).FirstOrDefault();

            return PartialView(DSKhachHangVM);
        }

        [HttpPost, ActionName("KhachHangEditPartialPost")]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> KhachHangEditPartialPost()
        {
            // from login session
            var user = HttpContext.Session.Gets<User>("loginUser").SingleOrDefault();

            string temp = "", log = "";

            if (ModelState.IsValid)
            {
                try
                {
                    #region log file
                    
                    var t = _unitOfWork.khachTourRepository.GetByIdAsNoTracking(x => x.Idkhach == DSKhachHangVM.KhachTour.Idkhach);
                    if (t.Stt != DSKhachHangVM.KhachTour.Stt)
                    {
                        temp += String.Format("- STT thay đổi: {0}->{1}", t.Stt, DSKhachHangVM.KhachTour.Stt);
                    }
                    if (t.Makh != DSKhachHangVM.KhachTour.Makh)
                    {
                        temp += String.Format("- Mã khách thay đổi: {0}->{1}", t.Makh, DSKhachHangVM.KhachTour.Makh);
                    }
                    if (t.Hoten != DSKhachHangVM.KhachTour.Hoten)
                    {
                        temp += String.Format("- Tên khách thay đổi: {0}->{1}", t.Hoten, DSKhachHangVM.KhachTour.Hoten);
                    }
                    if (t.Ngaysinh != DSKhachHangVM.KhachTour.Ngaysinh)
                    {
                        temp += String.Format("- Ngày sinh thay đổi: {0:dd/MM/yyyy}->{1:dd/MM/yyyy}", t.Ngaysinh, DSKhachHangVM.KhachTour.Ngaysinh);
                    }
                    if (t.Phai != DSKhachHangVM.KhachTour.Phai)
                    {
                        temp += String.Format("- giới tính thay đổi: {0}->{1}", t.Phai, DSKhachHangVM.KhachTour.Phai);
                    }
                    if (t.Quoctich != DSKhachHangVM.KhachTour.Quoctich)
                    {
                        temp += String.Format("- Quốc tịch thay đổi: {0}->{1}", t.Quoctich, DSKhachHangVM.KhachTour.Quoctich);
                    }
                    if (t.Hochieu != DSKhachHangVM.KhachTour.Hochieu)
                    {
                        temp += String.Format("- Hộ chiếu thay đổi: {0}->{1}", t.Hochieu, DSKhachHangVM.KhachTour.Hochieu);
                    }

                    if (t.Cmnd != DSKhachHangVM.KhachTour.Cmnd)
                    {
                        temp += String.Format("- CMND thay đổi: {0}->{1}", t.Cmnd, DSKhachHangVM.KhachTour.Cmnd);
                    }
                    if (t.Loaiphong != DSKhachHangVM.KhachTour.Loaiphong)
                    {
                        temp += String.Format("- Loại phòng thay đổi: {0}->{1}", t.Loaiphong, DSKhachHangVM.KhachTour.Loaiphong);
                    }
                    if (t.Diachi != DSKhachHangVM.KhachTour.Diachi)
                    {
                        temp += String.Format("- Địa chỉ thay đổi: {0}->{1}", t.Diachi, DSKhachHangVM.KhachTour.Diachi);
                    }
                    if (t.Dienthoai != DSKhachHangVM.KhachTour.Dienthoai)
                    {
                        temp += String.Format("- Điện thoại thay đổi: {0}->{1}", t.Dienthoai, DSKhachHangVM.KhachTour.Dienthoai);
                    }

                    
                    #endregion
                    // kiem tra thay doi
                    if (temp.Length > 0)
                    {

                        log = System.Environment.NewLine;
                        log += "=============";
                        log += System.Environment.NewLine;
                        log += temp + " -User cập nhật tour: " + user.Username + " vào lúc: " + System.DateTime.Now.ToString(); // username
                        t.Logfile = t.Logfile + log;
                        DSKhachHangVM.KhachTour.Logfile = t.Logfile;
                    }

                    // khachtour
                    _unitOfWork.khachTourRepository.Update(DSKhachHangVM.KhachTour);

SaleDoanInbound/Views/DSKhachHangs/DSKhachHangPartial.cshtml
@model DSKhachHangViewModel

<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                @*Sgtcode - <b>@Model.Tour.Sgtcode</b>*@

                <button type="button" data-tourid="@Model.Tour.Id" id="btnNewKhachHang" class="btn btn-outline-info btn-xs" title="Thêm mới"><i class="fas fa-plus"></i>Thêm mới</button>
            </h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">

            <div style="overflow-x:auto;">
                <table class="table mytable text-nowrap tblEMD" id="listAll">
                    <thead>
                        <tr class="table-info">
                            <th>#</th>
                            <th>STT</th>
                            <th>Mã</th>
                            <th>Họ tên</th>
                            <th>Ngày sinh</th>
                            <th>Phái</th>
                            <th>Điện thoại</th>
                            <th>Hộ chiếu</th>
                            <th>CMND</th>
                            <th>Quốc tịch</th>
                            <th>Loại phòng</th>
                            <th class="text-center">
                                Vé máy bay<br /><input type="checkbox" class="tfoot" style="display:none;" onchange="checkAll('tbKhachHang')" /><span class="tfoot" style="display:none"> | </span><a href="javascript:;" id="btSavedata" class="fa fa-save fa-lg tfoot" style="display:none;"></a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ListDsKhach)
                        {

                            <tr class="cursor-pointer ">

                                <td>
                                    <div class="btn-group text-white" role="group">

                                        <a class="text-primary btnEditKhachHang" title="Cập nhật" data-id="@item.Idkhach"><i class="fas fa-edit"></i></a>
                                        <span class="text-dark"> | </span>
                                        @*<a class="text-success" title="Chi tiết" asp-action="Details" asp-controller="BienNhans" asp-route-id="@item.Id" asp-route-tourId="@item.TourId" asp-route-strUrl="@Model.StrUrl"><i class="fas fa-list"></i></a>
                                            <span class="text-dark"> | </span>*@
                                        <form asp-action="Delete" asp-controller="DSKhachHangs" asp-route-id="@item.Idkhach" method="post">

                                            <span id="confirmDeleteSpan_@item.Idkhach" style="display: none">
                                                <span class="text-dark spanXoa">Hủy?</span>
                                                <button type="button" data-id="@item.Idkhach"  data-tourid="@Model.Tour.Id" class="btn btn-danger btn-xs btnXoaKhachHangPartial">Yes</button>
                                                <button type="button" class="btn btn-primary btn-xs" onclick="confirmDelete('@item.Idkhach', false)">No</button>
                                            </span>

                                            <span id="deleteSpan_@item.Idkhach">

                                                <button title="Xóa" type="button" class="text-danger border-0 bg-transparent btnHuy" onclick="confirmDelete('@item.Idkhach', true)"><i class="fas fa-trash-alt"></i></button>

                                            </span>
                                        </form>
                                    </div>
                                </td>

                                <td class="text-center">
                                    @item.Stt
                                </td>
                                <td>
                                    @item.Makh
                                </td>
                                <td>
                                    @item.Hoten
                                </td>
                                <td>
                                    @Html.Raw(item.Ngaysinh.HasValue ? item.Ngaysinh.Value.ToString("dd/MM/yyyy") : "/ /")
                                </td>
                                <td>
                                    @Html.Raw(item.Phai == true ? "Nam" : "Nữ")
                                </td>
                                <td>@item.Dienthoai</td>
                                <td>
                                    @item.Hochieu
                                </td>
                                <td>
                                    @item.Cmnd
                                </td>
                                <td>
                                    @item.Quoctich
                                </td>
                                <td>
                                    @item.Loaiphong
                                </td>
                                <td class="text-center">
                                    <input type="checkbox" checked="@item.Vmb" name="vmb" class="ckId" disabled />
                                </td>
                                <td style="display:none">
                                </td>
                            </tr>

                        }
                    </tbody>

                </table>
            </div>

        </div>
        <!-- /.card-body -->

    </div>
    <!-- /.card -->

</section>

<script src="~/js/Admin/DSKhachHang/indexController.js"></script>
<script src="~/js/Admin/Tours/indexController.js"></script>
<script>
    function confirmDelete(uniqueId, isDeleteClicked) {
        var deleteSpan = 'deleteSpan_' + uniqueId;
        var confirmDeleteSpan = 'confirmDeleteSpan_' + uniqueId;

        if (isDeleteClicked) {
            $('#' + deleteSpan).hide();
            $('#' + confirmDeleteSpan).show();

        } else {
            $('#' + deleteSpan).show();
            $('#' + confirmDeleteSpan).hide();
        }
    }
</script>

SaleDoanInbound/Views/DSKhachHangs/EditKhachHangPartial.cshtml
@model DSKhachHangViewModel
<!-- Main content -->
<section class="content">

    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><i class="fas fa-file text-info"></i> Cập Nhật Khách Hàng - <b>@Model.Tour.Sgtcode</b></h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button id="btnCloseKhachCreatePartial" type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">

            <form asp-action="CreateInvoicePartial" method="post" id="frmEditKhachHangPartial" autocomplete="off">
                <div class="p-4 border rounded">

                    <input asp-for="KhachTour.Idkhach" type="hidden" /> <!-- this field is required-->
                    <input asp-for="KhachTour.Sgtcode" type="hidden" /> <!-- this field is required-->

                    <div asp-validation-summary="All" class="text-danger"></div>

                    <div class="form-group row">

                        <div class="col-md-2">
                            <label asp-for="KhachTour.Stt" class="control-label"></label>
                            <input asp-for="KhachTour.Stt" class="form-control " id="txtStt" />
                            <span asp-validation-for="KhachTour.Stt" class="text-danger"></span>
                        </div>

                        <div class="col-md-2">
                            <label asp-for="KhachTour.Makh" class="control-label"></label>
                            <input asp-for="KhachTour.Makh" class="form-control " />
                            <span asp-validation-for="KhachTour.Makh" class="text-danger"></span>
                        </div>

                        <div class="col-md-3">
                            <label asp-for="KhachTour.Hoten" class="control-label"></label>
                            <input asp-for="KhachTour.Hoten" class="form-control " />
                            <span asp-validation-for="KhachTour.Hoten" class="text-danger"></span>
                        </div>

                        <div class="col-md-3">
                            <label asp-for="KhachTour.Ngaysinh" class="control-label"></label>
                            <input type="text" asp-for="KhachTour.Ngaysinh" class="form-control maskInput" />
                            <span asp-validation-for="KhachTour.Ngaysinh" class="text-danger"></span>
                        </div>

                        <div class="col-md-2 ">
                            <label asp-for="KhachTour.Phai" class="control-label"></label>
                            <select asp-for="KhachTour.Phai" class="form-control "
                                    asp-items="@(new SelectList(Model.GioiTinhs, "GioiTinhId", "GioiTinhName"))">
                            </select>
                            <span asp-validation-for="KhachTour.Phai" class="text-danger"></span>
                        </div>

                    </div>

                    <div class="form-group row">

                        <div class="col-md-3">
                            <label asp-for="KhachTour.Quoctich" class="control-label"></label>
                            <input asp-for="KhachTour.Quoctich" class="form-control " />
                            <span asp-validation-for="KhachTour.Quoctich" class="text-danger"></span>
                        </div>

                        <div class="col-md-3">
                            <label asp-for="KhachTour.Hochieu" class="control-label"></label>
                            <input asp-for="KhachTour.Hochieu" class="form-control" />
                            <span asp-validation-for="KhachTour.Hochieu" class="text-danger"></span>
                        </div>

                        <div class="col-md-3">
                            <label asp-for="KhachTour.Cmnd" class="control-label"></label>
                            <input asp-for="KhachTour.Cmnd" class="form-control " />
                            <span asp-validation-for="KhachTour.Cmnd" class="text-danger"></span>
                        </div>

                        <div class="col-md-3 ">
                            <label asp-for="KhachTour.Loaiphong" class="control-label"></label>
                            <input asp-for="KhachTour.Loaiphong" class="form-control" />
                            <span asp-validation-for="KhachTour.Loaiphong" class="text-danger"></span>
                        </div>

                    </div>

                    <div class="form-group row">

                        <div class="col-md-12">
                            <label asp-for="KhachTour.Diachi" class="control-label"></label>
                            <input asp-for="KhachTour.Diachi" class="form-control " />
                            <span asp-validation-for="KhachTour.Diachi" class="text-danger"></span>
                        </div>

                    </div>

                    <div class="form-group row">

                        <div class="col-md-3">
                            <label asp-for="KhachTour.Dienthoai" class="control-label"></label>
                            <input asp-for="KhachTour.Dienthoai" class="form-control " />
                            <span asp-validation-for="KhachTour.Dienthoai" class="text-danger"></span>
                        </div>

                        @*<div class="col-md-3">
                            <label asp-for="KhachTour.Visa" class="control-label"></label>
                            <input asp-for="KhachTour.Visa" class="form-control " />
                            <span asp-validation-for="KhachTour.Visa" class="text-danger"></span>
                        </div>

                        <div class="col-md-3">
                            <label asp-for="KhachTour.YeuCauVisa" class="control-label"></label>
                            <input asp-for="KhachTour.YeuCauVisa" class="form-control " />
                            <span asp-validation-for="KhachTour.YeuCauVisa" class="text-danger"></span>
                        </div>*@

                    </div>

                    <div class="form-group row">
                        <div class="form-group">
                            <button type="button" id="btnEditKhachHangPartialSubmit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
                            <button id="btnBackKhachHangEditPartial" type="button" class="btn btn-success"><i class="fas fa-backward"></i> Back</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>

    </div>

</section>


@*<script>

        $(function () {
            $(".datepicker").datepicker({
                dateFormat: 'dd/mm/yy'
            });
        });
    </script>*@
<script>
    $(function () {
        $('.select2').select2()
    });
    $(function () {
        $(".maskInput").mask("99/99/9999");

        //$('#AlertBox').removeClass('hide');
        //$('#AlertBox').delay(1000).slideUp(1000);
    });

</script>

<script src="~/js/Admin/KhachHangEditPartial/EditController.js"></script>
<script src="~/js/Admin/Tours/indexController.js"></script>
<!-- Validation -->
<script>
    var tourIdInCreateInvoicePartial = @Model.KhachHang.TourId; // send it to indexController
    @*$('#frmInvoiceCreatePartial').validate({
        //rules: {
        //    email: {
        //        required: true,
        //        email: true,
        //    },
        //    NgayDen: {
        //        required: true
        //    },
        //    chuDetour1: {
        //        required: true
        //    },
        //},
        //messages: {
        //    email: {
        //        required: "Please enter a email address",
        //        email: "Please enter a vaild email address"
        //    },
        //    NgayDen: {
        //        required: "Please provide a date"
        //    },
        //    chuDetour1: "Please enter value"
        //},
        errorElement: 'span',
        errorPlacement: function (error, element) {
            // add error text

            //error.addClass('invalid-feedback').removeClass('error');
            //element.closest('.chuDeTourGroup').append(error);
        },
        highlight: function (element, errorClass, validClass) {
            $(element).addClass('is-invalid');
        },
        unhighlight: function (element, errorClass, validClass) {
            $(element).removeClass('is-invalid');
        }
    });

    $('#ddlLoaiTien').rules('add', {
        required: true,
        messages: {
            // required: "Ngày đến không được để trống"
        }
    });

    $('#txtTyGia').rules('add', {
        required: true,
        messages: {
            // required: "Ngày đến không được để trống"
        }
    });

    //$('#btnCreateInvoicePartial').off('click').on('click', function () {
    //    //if ($('#frmInvoiceCreatePartial').valid()){
    //    //    alert('a');
    //    //};
    //});
*@
    $('#btnEditKhachHangPartialSubmit').off('click').on('click', function () {

        // if frm valid
        //if ($('#frmInvoiceCreatePartial').valid()) {
        var khachHang = $('#frmEditKhachHangPartial').serialize();
            $.ajax({
                type: "POST",
                url: "/DSKhachHangs/KhachHangEditPartialPost",
                data: khachHang,
                dataType: "json",
                success: function (response) {
                    if (response.status) {

                        toastr.success('Cập nhật khách hàng thành công!');

                        $('#khachHangEditPartial').hide(500);
                        @*$('tr .tdVal').click(function () {

                            tourId = @Model.Invoice.TourId;

                            var url = '/Tours/KeToan_TourInfoByTourPartial';
                            $.get(url, { tourId: tourId }, function (response) {

                                $('#tabs_KeToan_TourInfo').html(response);

                            });

                        });*@
                        indexController.Load_DSKhachHang(tourIdInCreateInvoicePartial);
                        $('#sDSKhach').show(500);
                    }
                    else {
                        toastr.error('Cập nhật khách hàng không thành công!');

                        //  debugger
                        // $('#createInvoiceModal').show();
                        // $('.createInvoicePartial').html(response);
                        //$('#createInvoiceModal').draggable();

                        //tourid = $(this).data('tourid');
                        //var url = '/Invoices/CreateInvoicePartial';
                        //$.get(url, { tourid: tourid }, function (response) {

                        //    $('#createInvoiceModal').show();
                        //    $('.createInvoicePartial').html(response);
                        //    $('#createInvoiceModal').draggable();

                        //});

                    }
                }
            });
        //}
    });

</script>

@*<style>
        #txtStt {
            -webkit-appearance: none;
            -moz-appearance: none;
        }
    </style>*@